package org.obsplatform.infrastructure.jobs.service;

public enum JobName {

    INVOICE("INVOICING"),
    REQUESTOR("REQUESTOR"),
    RESPONSOR("Responser"),
    SIMULATOR("SIMULATOR"),
    PUSH_NOTIFICATION("MESSAGING"),
    GENERATE_STATEMENT("STATEMENT"),
    MESSAGE_MERGE("MERGE_MESSAGE"),
    AUTO_EXIPIRY("AUTO_EXPIRY"), 
    Middleware("MIDDLEWARE"),
    EVENT_ACTION_PROCESSOR("EVENT_ACTIONS"),
    REPORT_EMAIL("REPORTER"),
    MAKE_STATMENT_PDF("PDF"),
    RADIUS("RADIUS"), 
    EXPORT_DATA("EXPORTDATA"),
    RESELLER_COMMISSION("RESELLERCOMMISSION"),
    REPROCESS("REPROCESS"),
    AGING_DISTRIBUTION("AGINGDISTRIBUTION"),
   // DISCONNECT_UNPAID_CUSTOMERS("DISCONNECT_UNPAID_CUSTOMERS"), 
    USAGE_CHARGES("USAGECHARGES"),
    EVO_BATCH_PROCESS("EVO_BATCH_PROCESS"),
    EVO_BATCH_PROCESS_DOWNLOAD("EVO_BATCH_PROCESS_DOWNLOAD"),
    SUSPENSION_Of_SERVICE("SUSPENSION_Of_SERVICE"),
    DISCONNECT_SERVICES_OF_UNPAID_CUSTOMERS("DISCONNECT_SERVICES_OF_UNPAID_CUSTOMERS"),
	FOLLOWUP_TICKETS("FOLLOWUP_TICKET"),
	FOLLOWUP_TO_OPEN("FOLLOWUP_TO_OPEN"),
    WORLDPAY_RECURRING_BATCH_PROCESS("WORLDPAY_RECURRING_BATCH_PROCESS"),
	LOG_FILES_REMOVE("LOG_FILES_REMOVE");


    private final String name;

    JobName(final String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}
